version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: xander
      POSTGRES_DB: habitsTrackerDB

    ports:
      -  "5433:5432"

    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: